apiVersion: v1
kind: Template
metadata:
  name: wp-cassandra-template
  annotations:
    description: Cassandra  cqlsh deploy
    tags: openshift, cassandra, worldpay

parameters:
  - name: OBJECT_NAME_PREFIX
    description: Name prefix for each object created
    required: true
    value: wp-cassandra
  - name: CONTAINER_IMAGE
    description: Image Name of the Container for Cassandra
    required: true
    value: rindukuri/wp-cassandra

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: app3-pv  

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${OBJECT_NAME_PREFIX}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ${OBJECT_NAME_PREFIX}
          
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-claim     
      spec:
        containers:
        - name: cassandra-cql
          image: ${CONTAINER_IMAGE}
          command:
          - "/opt/apache-cassandra/bin/docker-entrypoint.sh"
          - "--cluster_name=openstack-cluster"
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra-peers.waus.svc
            - name: CASSANDRA_CLUSTER_NAME
              value: OpenStack cluster
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: OpenStack rac
          ports:
          - name: cql-port
            containerPort: 9042
          - name: thift-port
            containerPort: 9160
          - name:  intra-node
            containerPort: 7000
          - name: tls-intra
            containerPort: 7001    
        volumeMounts:
          - name: cassandra-data
            mountPath: "/var/lib/cassandra/data"
             
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - cassandra-cql
        from:
          kind: ImageStream
          name: ${OBJECT_NAME_PREFIX}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: cassandra-peers
    name: cassandra-peers
  spec:
    clusterIP: None
    ports:
      - port: 7000
        name: intra-node
      - port: 7001
        name: tls-intra
    selector:
      app: ${OBJECT_NAME_PREFIX}      
- apiVersion: v1
  kind: Service
  metadata:
    name: cassandra-cql
  spec:
    type: LoadBalancer
    ports:
    - port: 9042
      name: cql-port
      nodePort: 31105
    selector:
      app: ${OBJECT_NAME_PREFIX}      