apiVersion: v1
kind: Service
metadata:
    name: cassandra-peers
spec:
  ports:
    - port: 7000
      name: intra-node
      targetPort : 7000
      protocol: TCP
    - port: 7001
      name: tls-intra
      targetPort : 7001
      protocol: TCP
    - port: 9042
      name: cql-port 
      targetPort : 9042
      protocol: TCP     
  selector:
    name: wp-cassandra  

